POST  http://localhost:3000/admin/
Content-Type: application/json

{
    "email":"root@gmail.com",
    "password":"jmaker00643"
}

###

GET  http://localhost:3000/admin/

###

POST http://localhost:3000/admin/login
Content-Type: application/json

{
    
}